# Generated by Django 5.1.6 on 2025-02-21 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(choices=[('Algebra', 'Algebra'), ('Modelizacion', 'Modelizacion'), ('Funiones_Graficas', 'Funiones_Graficas'), ('Logica', 'Logica')], max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=150, null=True)),
                ('numero', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('respuestaOK', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documento', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=150, null=True)),
                ('tipo_usuario', models.CharField(default='profesor', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('celular', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=150, null=True)),
                ('tipo_usuario', models.CharField(default='estudiante', max_length=10)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostico.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('seleccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True)),
                ('fecha', models.DateField(auto_now=True)),
                ('estudianteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.estudiante')),
                ('preguntaFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostico.pregunta')),
            ],
        ),
    ]
