# Generated by Django 5.1.6 on 2025-02-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='block',
            field=models.CharField(choices=[('Algebra', 'Algebra'), ('Modelizacion', 'Modelizacion'), ('Funciones_Graficas', 'Funciones_Graficas'), ('Logica', 'Logica')], max_length=20, null=True),
        ),
    ]
