# Generated by Django 5.1.6 on 2025-03-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_pregunta_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='seleccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Ninguna', 'Ninguna')], max_length=20, null=True),
        ),
    ]
